# general configuration
robot_name: Virtual
robot_ip: localhost
local_interface_name: "wlp111s0"
socket_timeout: 0.1 # for all sockets (ROS, etc.)
window_border: true


# periods to run things
ping_period: 0.25 # in seconds
ping_timeout: 0.5 # in seconds
ros_control_period: 500.0 # in ms
ros_period: 500.0 # ?
max_bad_ping: 4

# ROS topics
topics: []

# gstreamer
gstreamer_topic: "/gstreamer_service"
rtp_port: 5000 # streamer robot->station (video)
rtp_timeout: 2.0 # in seconds
rtcp_port: 5001 # streamer robot->station (control) # deprecated
gst_clock: true # should we display the clock on the video
gst_verbose: false
gstreamer_ip: "localhost" # deprecated
rtp_host: "localhost" # deprecated
ntp_server: 'time.apple.com'
use_rtcp: false # deprecated

# plot configurations
plot_videostream_period: 10
plot_network_period: 250.0 # in ms
plot_ping_max: 1 # 1 ms is already a lot for localhost
plot_fps_max: 60
plot_downstream_max: 10
plot_upstream_max: 2
plot_bitrate_max: 2
plot_jitter_max: 5
plot_delay_max: 100 # ms
